### ISSUE TITLE
Add default overridable config for running solutions in particular language

### ISSUE THREAD

**Issue by ellnix** [Andriamanitra/clash#19]
It would be great if there was a lookup table with language names and the build & run commands that the tool automatically searches for. Some ideas:

```bash
# changes the default language to C
clash language c
```

```bash 
clash run 
# runs `sol.{language_file_ext}` with default language
```

```bash
clash run --language rust
clash run -l rust
# runs sol.rs with rust
```

Ideally there would be a config file in `$XDG_CONFIG_HOME/clash` for Linux and `%Appdata%/whatever` for Windows like:

```yaml
# languages.yml
ruby:
  run: ruby sol.rb
c:
  build: gcc sol.c
  run: ./sol
rust:
  run: cargo run --release
  workspace: rust
  code_origin: sol.rs
  code_destination: src/main.rs
```

```dirtree
- workspaces/
  - rust/
    - src/
    - Cargo.toml
```

The workspace feature would allow for supporting non standard libraries in languages like Rust. The workflow would be:
- Edit `sol.rs`
- `clash run`
  - `cp {config['rust']['code_origin']} CONFIG_FOLDER/workspaces/{config['rust']['workspace']}/{config['rust']['code_destination']}`, 
  i. e. `cp sol.rs CONFIG_FOLDER/workspaces/rust/src/main.rs`
  - `{config['rust']['run']}`,
    i. e. `cargo run --release`
  - Evaluate solution
